# THE PATH
data:
  raw_data: "data/raw/WEATHER.csv"

# THE OLUMNS
the_time: "DATE"
the_target: "T"
the_features: ["T", "P", "RH"]

# MODEL PARAMETERS | # 12 MONTHS OR PERIODS
test_size: 12
the_arima_order: [1, 1, 1] 
the_mlflow : "temperature_forecast"
